version: '3.8'

services:
  delivery-api:
    build:
      context: .
      dockerfile: ./testes.Dockerfile
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
    command: ["mvn", "spring-boot:run"]